### ISSUE TITLE
WHCMS automation

### ISSUE THREAD

**Issue by glowfishDE** [mhofer117/ispconfig-ddns-module#10]
Hi Marcel,

not exactly an issue, but would you offer the automation/integration into WHCMS ? I would also pay for it if you dont want to bring this as a public feature. So a customer can order a DNS entry via WHCMS and your DDNS module is generating the token given on the customers order as well as sends back the necessary information to the customers WHCMS "ordered product" page.

Please let me know :)

**Comment by mhofer117** [comment]
Hi glowfishDE

Sorry ich bin aktuell nicht an Auftragsarbeit interessiert.
