### ISSUE TITLE
Typo on Standard update URL?

### ISSUE THREAD

**Issue by mperaya** [mhofer117/ispconfig-ddns-module#3]
First of all, nice work well done.

In token helper dialog, the Simple mode generated URL to copy is https://my domain/ddns/update.php?rest_of_query but the Standard update URL shows https://my domain/?rest_of_query.
If I copy the Standard update URL and paste it on browser, and modify the new IP ADDRES, I'm redirected to ISPConfig login page and the module does not work at all.
If I add the /ddns/update.php to the web resquest, it works like a charm.

I'ts an error or maybe I've forgotten anithing in config?

Hope this helps.

**Comment by mhofer117** [comment]
Thanks for reporting.
Yes this was indeed a bug introduced in v1.2.0.
I have just published a hotfix v1.2.1.

Please update and try again.
