### ISSUE TITLE
Missing myip fallback

### ISSUE THREAD

**Issue by remkohat** [mhofer117/ispconfig-ddns-module#6]
If I'm not mistaken you stated yesterday that when the myip parameter is missing in the uri the script falls back to the ip from where the request originated.
I think yesterday's update might have broken something on that subject.

My Zyxel router at home has a by my ISP customized firmware installed.
I haven't got a clue if a variable for my ip exists and what it might be. Google didn't help one bit on the matter.
![image](https://user-images.githubusercontent.com/94494764/220335386-1b3ca4fc-81d6-422f-a9b6-3cd2b3c4f31c.png)

So I thought that it shouldn't have to be a problem as the script should fall back to the requester's ip.
Unfortunately I was wrong.

I see the expected uri in the logs `/nic/update?hostname=<host.ddnsdomain.tld>` originating from my home ip.
But nothing is updated in the dns.

When I change `ispconfig.tld/nic/update` to `ispconfig.tld/nic/update?myip=<ip>` in the router config, so the uri becomes `/nic/update?myip=<ip>&hostname=<host.ddnsdomain.tld>`, the dns is updated as expected.

**Comment by mhofer117** [comment]
You are right the dyndns implementations currently did not check the remote-ip, as it was expected the `myip` query string is always set.
However this is unrelated to the change yesterday.

Please try the latest release v1.2.4 where this behaviour was added.

**Comment by remkohat** [comment]
The update seems to have worked correctly.
Dns is updated with my current ip.
