### ISSUE TITLE
Trying to setup with FritzBox 7590 / Fritz OS 7.50 fails

### ISSUE THREAD

**Issue by glowfishDE** [mhofer117/ispconfig-ddns-module#8]
Hi,

i am trying to run this with my FritzBox 7590 on Fritz OS 7.50.

I am surely doing something wrong because it is not updating the A-Record for subdomain.domain.tld (example) via the FritzBox even when i redial and let it have a new IP.

It works with the simple mode url: https://dnsupdate.domain.tld/ddns/update.php?token=xxxxxxxxxxxxxxx
Also works with the standard update url: https://dnsupdate.domain.tld/ddns/update.php?zone=domain.tld.&type=A&record=subdomain&data=YOUR_IP_ADDRESS&token=xxxxxxxxxxxxxxxxxx

I try to figure out what i have to enter into the FritzBox. I have this mask:

<img width="419" alt="image" src="https://user-images.githubusercontent.com/44566242/231817127-14cb9d30-fdd0-4fc3-b511-a64b6637eac6.png">

As the update URL i have tried the "DynDns1 / DynDns2 updates" value/url:

https://dnsupdate.domain.tld/nic/update?hostname=subdomain.domain.tld&myip=YOUR_IP_ADDRESS

For the Domainname field i would use what i get from the "Hostname" Value of the module in ISPConfig: subdomain.domain.tld
Username i think it has to be exactly the word "none" (without quotation marks)
Password should be the long generated token.

The generated token seems to be good. I allow to update the A-Record and limit it to the subdomain A-record Ipv4 only.
Since the standard / simple mode URL can update it, it seems not to be a problem with the configuration of the token.

I think i´m filling in the wrong values in the fritzbox.

My ISPconfig3 Setup is running on Port 8080 and i have a proxy page like it is described in the setup.

I am using Apache2 as a webserver.

Hope that helps

**Comment by mhofer117** [comment]
So I gather you've got it working now?

YOUR_IP_ADDRESS is different for each router/Client. According to the [fritzbox docs](https://avm.de/service/wissensdatenbank/dok/FRITZ-Box-7590/30_Dynamic-DNS-in-FRITZ-Box-einrichten/)  you need to set `<ipaddr>` for IPv6 or `<ip6addr>` for IPv6.

For some clients it appears you only provide the hostname and all parameters are auto-generated.

If you can provide a (redacted) Screenshot I would like to add it to the examples wiki page at https://github.com/mhofer117/ispconfig-ddns-module/wiki/Examples

**Comment by glowfishDE** [comment]
Hi Marcel,

yeah - i got it flying now.

I created a small descriptive screenshot for you. Feel free to use it :)

<img width="787" alt="image" src="https://user-images.githubusercontent.com/44566242/231830335-88b78c52-c71e-43bf-b751-f3284cdc48d8.png">

**Comment by glowfishDE** [comment]
PS: I´ve updated aboves comments to show the correct values so it is more clear what i meant before.

**Comment by mhofer117** [comment]
Thank you for providing the screenshot!

Note that the username does not matter, you can put anything there.

**Comment by glowfishDE** [comment]
Hi, 

two questions remain:

1) do you have to put a username at all or can you leave it blank too?
2) could you reflect the `<ipaddr>` value for the URL for FritzBoxes somehow in the token_list Webpage ? I could change the en_ddns_token_list.lng file and modify the `"url_ip_placeholder_txt"` variable but this also changes the value for the standard method update URL which renders it unfunctional than.

I would really appreciate some working URL that works for FritzBoxes that i can just copy&paste from the token list so i dont have to change the url_ip_placeholder in each URL manually when i create a new account.

maybe you could add something like `"fritzbox_url_ip_placeholder_txt"` and add = `<ipaddr>` and display a separate URL with a copy&paste button on the token list website.

Example:

<img width="217" alt="image" src="https://user-images.githubusercontent.com/44566242/231901093-2781f942-7e1a-497f-b938-cee5854a6b14.png">

Thanks alot :)

**Comment by mhofer117** [comment]
1. I believe Username could also be blank, but depending on the client, some value is required. That's why I put "none" as an example.
2. The issue is that YOUR_IP_ADDRESS is a placeholder and will be different on all routers/clients.

I would rather not display separate URLs for all possible vendors to keep the UI as simple as possible.

If you change the translation value for it as you suggested, it should work. Why does it render the standard update URL useless? That placeholder needs to be replaced anyway by the user.

**Comment by glowfishDE** [comment]
Ah you are right :) Ok - than i think i know how to use it in the future! 

Thank you!
