### ISSUE TITLE
Data Log History

### ISSUE THREAD

**Issue by thompol** [mhofer117/ispconfig-ddns-module#9]
It seems like the changes to the dns_rr table are not logged in the Data Log History of ISPConfig. I think this would be a very welcome addition, so you can see when the last changes were done easily.

**Comment by mhofer117** [comment]
Just checked and the data log history entries are created on my server for both dns_rr and dns_soa updates.
Are you sure the DNS entry was actually updated and the IP was not already correct?

**Comment by mhofer117** [comment]
The only issue I see is it is logged for the admin user, not the user the token is assigned to.
Will check if I can fix that.

**Comment by mhofer117** [comment]
With the latest release v1.3.0, the correct user should be logged.

**Comment by thompol** [comment]
You are correct, thanks. Great and quick work!
